using DifyAI.ObjectModels;
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace DifyAI.Json
{

    [JsonSourceGenerationOptions(
        PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]

    [JsonSerializable(typeof(ApplicationMetaRequest))]
    [JsonSerializable(typeof(ApplicationMetaResponse))]
    [JsonSerializable(typeof(ApplicationParametersRequest))]
    [JsonSerializable(typeof(ApplicationParametersResponse))]
    [JsonSerializable(typeof(AudioToTextRequest))]
    [JsonSerializable(typeof(AudioToTextResponse))]
    [JsonSerializable(typeof(ChatCompletionRequest))]
    [JsonSerializable(typeof(ChatCompletionResponse))]
    [JsonSerializable(typeof(ChunkCompletionAgentMessageResponse))]
    [JsonSerializable(typeof(ChunkCompletionAgentThoughtResponse))]
    [JsonSerializable(typeof(ChunkCompletionErrorResponse))]
    [JsonSerializable(typeof(ChunkCompletionMessageEndResponse))]
    [JsonSerializable(typeof(ChunkCompletionMessageFileResponse))]
    [JsonSerializable(typeof(ChunkCompletionMessageReplaceResponse))]
    [JsonSerializable(typeof(ChunkCompletionMessageResponse))]
    [JsonSerializable(typeof(ChunkCompletionNodeFinishedResponse))]
    [JsonSerializable(typeof(ChunkCompletionNodeStartedResponse))]
    [JsonSerializable(typeof(ChunkCompletionResponse))]
    [JsonSerializable(typeof(ChunkCompletionUnknownResponse))]
    [JsonSerializable(typeof(ChunkCompletionWorkflowFinishedResponse))]
    [JsonSerializable(typeof(ChunkCompletionWorkflowStartedResponse))]
    [JsonSerializable(typeof(CompletionData))]
    [JsonSerializable(typeof(CompletionExecutionMetadata))]
    [JsonSerializable(typeof(CompletionFile))]
    [JsonSerializable(typeof(CompletionMetadata))]
    [JsonSerializable(typeof(CompletionNodeFinishedData))]
    [JsonSerializable(typeof(CompletionNodeStartedData))]
    [JsonSerializable(typeof(CompletionRequest))]
    [JsonSerializable(typeof(CompletionResponse))]
    [JsonSerializable(typeof(CompletionUsage))]
    [JsonSerializable(typeof(CompletionWorkflowFinishedData))]
    [JsonSerializable(typeof(CompletionWorkflowStartedData))]
    [JsonSerializable(typeof(Conversation))]
    [JsonSerializable(typeof(ConversationDeleteRequest))]
    [JsonSerializable(typeof(ConversationListRequest))]
    [JsonSerializable(typeof(ConversationListResponse))]
    [JsonSerializable(typeof(ConversationRenameRequest))]
    [JsonSerializable(typeof(ConversationRenameResponse))]
    [JsonSerializable(typeof(DatasetCreateRequest))]
    [JsonSerializable(typeof(DatasetDeleteRequest))]
    [JsonSerializable(typeof(DatasetDocument))]
    [JsonSerializable(typeof(DatasetListRequest))]
    [JsonSerializable(typeof(DatasetListResponse))]
    [JsonSerializable(typeof(DocumentCreateByFileRequest))]
    [JsonSerializable(typeof(DocumentCreateByTextRequest))]
    [JsonSerializable(typeof(DocumentDeleteRequest))]
    [JsonSerializable(typeof(DocumentEmbeddingRequest))]
    [JsonSerializable(typeof(DocumentEmbeddingResponse))]
    [JsonSerializable(typeof(DocumentListRequest))]
    [JsonSerializable(typeof(DocumentListResponse))]
    [JsonSerializable(typeof(DocumentResponse))]
    [JsonSerializable(typeof(DocumentSegmentAddRequest))]
    [JsonSerializable(typeof(DocumentSegmentDeleteRequest))]
    [JsonSerializable(typeof(DocumentSegmentsItem))]
    [JsonSerializable(typeof(DocumentSegmentListRequest))]
    [JsonSerializable(typeof(DocumentSegmentResponse))]
    [JsonSerializable(typeof(DocumentSegmentUpdateRequest))]
    [JsonSerializable(typeof(DocumentUpdateByFileRequest))]
    [JsonSerializable(typeof(DocumentUpdateByTextRequest))]
    [JsonSerializable(typeof(FileUploadOptions))]
    [JsonSerializable(typeof(FileUploadRequest))]
    [JsonSerializable(typeof(FileUploadResponse))]
    [JsonSerializable(typeof(Message))]
    [JsonSerializable(typeof(MessageFeedback))]
    [JsonSerializable(typeof(MessageFeedbackRequest))]
    [JsonSerializable(typeof(MessageFile))]
    [JsonSerializable(typeof(MessageHistoryRequest))]
    [JsonSerializable(typeof(MessageHistoryResponse))]
    [JsonSerializable(typeof(MessageSuggestedRequest))]
    [JsonSerializable(typeof(MessageSuggestedResponse))]
    [JsonSerializable(typeof(ParameterOptions))]
    [JsonSerializable(typeof(RequestBase))]
    [JsonSerializable(typeof(RetrieverResource))]
    [JsonSerializable(typeof(SensitiveWordAvoidanceParameterOptions))]
    [JsonSerializable(typeof(StopCompletionRequest))]
    [JsonSerializable(typeof(SystemParametersOptions))]
    [JsonSerializable(typeof(TextToAudioRequest))]
    [JsonSerializable(typeof(TextToAudioResponse))]
    [JsonSerializable(typeof(TextToSpeechParameterOptions))]
    [JsonSerializable(typeof(UserInputFormOptions))]
    
    [JsonSerializable(typeof(Error))]
    [JsonSerializable(typeof(DatasetResponse))]
    [JsonSerializable(typeof(EmptyRequest))]
    [JsonSerializable(typeof(DocumentSegmentUpdateResponse))]
    //[JsonSerializable(typeof(DatasetCreateResponse))]
    //[JsonSerializable(typeof(DatasetProcessRules))]
    public partial class DifyAIJsonContext : JsonSerializerContext
    {
    }
}
